services:
  postgres_container:
    container_name: postgres-go
    image: postgres:16
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: gotest
    ports:
      - "5433:5432"
  
  app:
    container_name: go
    build: .
    depends_on:
      - postgres_container
    env_file:
      - .env
    ports:
      - "5001:5001"